repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: tflint
        name: tflinting
        files: \.tf
        entry: bash -c "find . -type f -name '*.tf' | xargs -I % dirname % | sort -u | xargs -I '{}' bash -c 'tflint {}'"
        language: system
        verbose: true
