export const Containers = [
  {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited transactions with zero fees',
    description:
      'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/fast-car.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
  },
  {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Unlimited transactions with zero fees',
    description:
      'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/fast-car.svg').default,
    alt: 'Piggybank',
    dark: false,
    primary: false,
    darkText: true,
  },
  //   {
  //     id: 'services',
  //     lightBg: true,
  //     lightText: false,
  //     lightTextDesc: false,
  //     topLine: 'Premium Bank',
  //     headline: 'Unlimited transactions with zero fees',
  //     description:
  //       'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  //     buttonLabel: 'Start now',
  //     imgStart: false,
  //     img: require('../../images/fast-car.svg').default,
  //     alt: 'Paper',
  //     dark: false,
  //     primary: false,
  //     darkText: true,
  //   },
  {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Unlimited transactions with zero fees',
    description:
      'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/fast-car.svg').default,
    alt: 'Piggybank',
    dark: false,
    primary: false,
    darkText: true,
  },
];
